@startjson

title JSON Data Ermolaev
{
  "Users": {
    "id": "1",
    "login": "Mak",
    "Requests": [
    {
    "id": "1",
    "purpose": "Які вправи мені краще використовувати щоб звук при співі був чище?",
    "user id": 1
    },
    {
    "id": "2",
    "purpose": "Які мені ліки краще використовувати якщо болить живіт?",
    "user id": 1
    }
  ]
  },
  "Sing Experts": {
    "id": "1",
    "name": "Іван"
  },
  "Medical Consultants": {
    "id": "1",
    "name": "Доктор Ангелина"
  },
  "Responses to Requests": [
    {
    "id": "1",
    "response text": "Вправи на низхідний звукоряд від домінанти до тоніки можна  співати  зі  словами: легкий  вітерець,  сонечко  моє, а  гаму  в  низхідному  та висхідному  напрямку  співати  з  текстом: вниз  під  гірку  покотились,  знову  в  гору піднялись.",
    "request id": 1
    },
    {
    "id": "2",
    "response text": "Допомагають зняти біль такі медикаменти: спазмолітики: Дротаверин, Но-шпа, Тримедат, Необутин ферменти: Мезім форте, Креон, Фестал, Панкреатин, Ерміталь.",

    "request id": 2
    }
  ]
}

@endjson
