@startuml

hide circle
title UML Concept Classes

Class User {
    login
}

Class SingRequest {
    requestText
}

Class SingExpert {
    name
}

Class MedicalConsultantRequest {
    requestText
}

Class MedicalConsultant {
    name
}

User <|-- SingExpert
User"1" --> "*"SingRequest : send
SingExpert"1" --> "*"SingRequest : review
User <|-- MedicalConsultant
User"1" --> "*"MedicalConsultantRequest : send
MedicalConsultant"1" --> "*"MedicalConsultantRequest : review

@enduml
