@startuml
title Activity Diagram Ermolaev

start
:The user sends a request for medical consultation;
if (Successfull?) then (Yes)
  :The medical consultant responds to the request;
  :Appoints a consultation time;
  if (Successfull?) then (Yes)
    :The user receives a response;
  else (No)
    :Error message;
  endif
else (No)
  :Error message;
endif
stop

@enduml
