name: ProgramCode
on: 
  push:
    branches: LW11
jobs:
  ProgramCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute
        uses: github/super-linter@v4
        env:
          VALIDATE_KOTLIN: true
          FILTER_REGEX_INCLUDE: ./*.kt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
